#!/usr/bin/env node
import fs from 'node:fs';import crypto from 'node:crypto';
const date=process.env.SELF_PRODUCE_DATE||process.env.PUBLICATION_DATE||process.env.PUBLISH_DATE||new Date().toISOString().slice(0,10);
const reportPath='data/continuity/post_2026_continuity_report.json';
if(date<'2027-01-01'){fs.writeFileSync(reportPath,JSON.stringify({schema_version:'1.0',run_date:date,status:'NOT_ACTIVE_BEFORE_2027',records_changed:0},null,2)+'\n');console.log('[continuity:harden] blocked before 2027');process.exit(0);}
const calPath='data/content/content_calendar.json',cal=JSON.parse(fs.readFileSync(calPath,'utf8')),id=`dprs-${date}-self-produced`,item=cal.items.find(x=>x.id===id);if(!item)throw new Error(`Native future item missing: ${id}`);
const topics=[
 ['recovery-housing-expectations','Understanding recovery housing expectations before move-in','What should someone understand about recovery housing expectations before move-in?','Recovery housing expectations can include substance-free living, routines, shared responsibilities, guest rules, accountability, and communication. The useful next step is to ask the provider directly what is required, what support is available, and what would make the setting a safe fit.','people comparing recovery housing','recovery-housing'],
 ['referral-handoff','Preparing a clear recovery housing referral handoff','What information helps a recovery housing referral move forward clearly?','A useful referral handoff separates emergency and clinical needs from housing needs, confirms the person’s current safety, gathers basic contact and treatment-transition information, and asks the provider about fit and availability without sending sensitive details through an unsecured form.','referral partners and families','referral-partner-journey'],
 ['family-boundaries','Supporting recovery without taking over','How can families support recovery without taking over every decision?','Families can support recovery by staying connected, setting clear boundaries, encouraging qualified help, and focusing on specific next steps rather than trying to control every outcome. Immediate danger and crisis needs still belong with emergency or crisis professionals.','families supporting a loved one','family-support'],
 ['daily-structure','Rebuilding a steady daily structure in recovery','What can help someone rebuild a steady daily structure in recovery?','A steady recovery routine usually starts with a few repeatable anchors: safe housing, sleep and meal structure, appointments, transportation, supportive contact, and one realistic task at a time. The goal is not perfection; it is a safer day with fewer avoidable gaps.','adults rebuilding stability','gen-z-millennial-recovery'],
 ['identity-respect','Choosing identity-respecting recovery support','What should someone look for in identity-respecting recovery support?','Identity-respecting recovery support should communicate dignity, safety, clear expectations, privacy, and a willingness to address discrimination or exclusion. People should be able to ask how a provider supports culture, gender identity, sexual orientation, faith, disability, and belonging without being shamed.','LGBTQ+ and minority recovery communities','lgbtq-recovery-support'],
 ['discharge-planning','Planning the transition from treatment to recovery housing','What should be considered when planning a transition from treatment to recovery housing?','A treatment-to-housing transition is easier to navigate when discharge timing, medications, transportation, follow-up care, housing expectations, emergency contacts, and referral responsibility are clarified before the move. Recovery housing does not replace licensed clinical care.','people leaving treatment and referral teams','recovery-housing'],
 ['setback-next-step','Choosing the next safe step after a setback','What is a useful next step after a recovery setback?','After a setback, the first task is safety rather than shame. Identify whether emergency or crisis support is needed, reconnect with qualified care when appropriate, review the living environment, and choose one concrete action that reduces risk in the next 24 hours.','people recovering after a setback','recovery-housing'],
 ['provider-questions','Questions to ask a recovery housing provider','What questions should someone ask a recovery housing provider?','Useful questions cover eligibility, current availability, costs, house expectations, medication policies, transportation, length of stay, peer support, discharge planning, privacy, grievance procedures, and what happens when someone needs a higher level of care.','people and families comparing options','recovery-housing'],
 ['young-adult-stability','Young-adult recovery support for work, school, and housing','How can young adults plan for work, school, and housing during recovery?','Young adults can reduce overwhelm by separating immediate safety and housing needs from longer-term work or school goals, then building a schedule around appointments, transportation, supportive relationships, and one achievable responsibility at a time.','young adults in recovery','gen-z-millennial-recovery'],
 ['women-safety','Safety and dignity in women-centered recovery support','What should women look for in recovery support and housing?','Women-centered recovery support should make safety, dignity, privacy, clear boundaries, trauma awareness, childcare or family realities, transportation, and access to qualified care discussable without pressure or promises. Fit should be evaluated directly with the provider.','women seeking recovery support','women-recovery-support'],
 ['privacy-referral','Protecting privacy during a recovery referral','How can someone protect privacy when asking for recovery support?','A general website contact form should not be treated as a clinical intake or a secure place for detailed health information. Start with the minimum information needed to request a conversation, then use the provider’s approved secure process for sensitive details.','people and referral partners','referral-partner-journey'],
 ['belonging-community','Building healthy connection and belonging in recovery','Why do connection and belonging matter in recovery support?','Healthy connection can reduce isolation and make routines easier to sustain, but community should still include boundaries, consent, privacy, and access to qualified help. The right setting supports belonging without demanding disclosure or promising a specific outcome.','people rebuilding community','minority-recovery-support'],
 ['transportation-access','Planning transportation and appointment access','What transportation questions matter when considering recovery housing?','Transportation can affect treatment follow-up, employment, court obligations, family responsibilities, and daily stability. Ask what transportation is available, what residents must arrange themselves, and how missed rides or appointments are handled.','people comparing recovery housing','recovery-housing'],
 ['cost-conversation','Preparing for a recovery housing cost conversation','What should someone ask about recovery housing costs?','Before committing, ask for the current price, payment schedule, deposits, included services, refund or discharge policies, transportation costs, and any outside expenses. Do not assume insurance coverage or financial assistance without written confirmation.','people and families planning next steps','recovery-housing'],
 ['crisis-boundary','Knowing when recovery housing is not the immediate answer','When is recovery housing not the immediate answer?','Recovery housing is not emergency response, detox, inpatient treatment, or crisis stabilization. Immediate danger belongs with 911; mental health or substance use crisis support belongs with 988; urgent medical needs belong with qualified medical professionals.','people deciding what help is needed','recovery-housing'],
 ['work-reentry','Returning to work while rebuilding recovery structure','How can someone prepare to return to work during recovery?','A work re-entry plan can start with sleep, transportation, appointments, realistic hours, supportive contact, and a response plan for stress or setbacks. Employment goals should fit the person’s current safety and care needs rather than replacing them.','adults returning to work','gen-z-millennial-recovery']
];
const lenses=['a practical checklist','a decision framework','questions to ask','common mistakes to avoid','a 24-hour next-step plan','a family conversation guide','a referral-partner handoff','a dignity-first review'];
const decisionContexts=['before the first provider call','during treatment discharge planning','while comparing housing options','when a family needs clearer boundaries','after a recovery setback','while rebuilding work or school routines','when privacy and safe communication matter','during a referral handoff','when transportation or appointments are a concern','while evaluating fit and availability','when immediate needs feel overwhelming','while planning the next 30 days'];
const seed=crypto.createHash('sha256').update(date).digest();const topic=topics[seed.readUInt16BE(0)%topics.length],lens=lenses[seed.readUInt16BE(2)%lenses.length],decisionContext=decisionContexts[seed.readUInt16BE(4)%decisionContexts.length];
const [topicId,baseTitle,question,directAnswer,audience,queryFamilyId]=topic;
const d=new Date(`${date}T00:00:00Z`),dow=d.getUTCDay(),day=d.getUTCDate(),month=d.getUTCMonth()+1,next=new Date(Date.UTC(d.getUTCFullYear(),month,0)),isQuarter=[3,6,9,12].includes(month)&&day===next.getUTCDate();
const contentType=isQuarter?'quarterly_whitepaper':day===1?'monthly_pillar':dow===2?'weekly_article':'daily_resource';
const typeLabel={daily_resource:'Daily recovery resource',weekly_article:'Weekly recovery article',monthly_pillar:'Monthly recovery guide',quarterly_whitepaper:'Quarterly recovery reference'}[contentType];
const slug=`${date}-${topicId}-${lens.replace(/[^a-z0-9]+/gi,'-').replace(/^-|-$/g,'').toLowerCase()}-${decisionContext.replace(/[^a-z0-9]+/gi,'-').replace(/^-|-$/g,'').toLowerCase()}`;
const title=`${baseTitle} ${decisionContext}: ${lens}`;
const commonBoundary='This resource is general recovery-support education. It is not a substitute for professional medical advice, diagnosis, treatment, detox, therapy, emergency care, or a promise that a service is available. Call 911 for immediate danger and call or text 988 for mental health or substance use crisis support.';
Object.assign(item,{title,slug,routeTarget:`/blog/${slug}/`,contentType,theme:typeLabel,audience,queryFamilyId,citationStrategyPillar:contentType==='quarterly_whitepaper'?'source_trust':contentType==='monthly_pillar'?'topical_depth':contentType==='weekly_article'?'answer_extraction':'distribution_flywheel',priorityScore:contentType==='quarterly_whitepaper'?95:contentType==='monthly_pillar'?82:contentType==='weekly_article'?72:60,summary:`${typeLabel} about ${baseTitle.toLowerCase()} ${decisionContext}, organized as ${lens}.`,directAnswer,answerSurface:{question,answer:directAnswer},requiredDisclaimers:['medical','outcomes','service_status'],humanizedIntro:`Recovery decisions can feel urgent, personal, and difficult to sort through, especially ${decisionContext}. ${directAnswer} This ${typeLabel.toLowerCase()} uses ${lens} so the reader can identify what belongs in a housing conversation, what belongs with a referral or clinical professional, and what belongs with emergency or crisis support. It avoids shame, unsupported promises, and assumptions about availability or licensure.`,sections:[
 {heading:'Short answer',body:`${directAnswer} The answer should be confirmed against the person’s current safety, the provider’s written expectations, and the actual services available at the time of contact. Dianne’s Place materials remain focused on recovery housing, referral support, and general education while expanded licensed services are still in development.`},
 {heading:`Use ${lens}`,body:`Start by writing down the decision in one sentence, the information that is already known, and the questions that still need a direct answer. Separate urgent safety needs from non-emergency housing or referral questions. Ask for written expectations where possible, and avoid sending detailed health information through a general website form.`},
 {heading:'Questions that make the next conversation clearer',body:`Ask what the provider offers now, who may be eligible, whether space is currently available, what the daily expectations are, what costs or documents are required, how referrals are handled, and what happens when someone needs emergency, medical, detox, or licensed clinical care beyond the provider’s role.`},
 {heading:'Common mistakes to avoid',body:`Do not assume that recovery housing is treatment, that a website form is a secure clinical intake, that availability is guaranteed, or that one setting fits every person. Avoid making the person prove worthiness through shame. A better process uses clear facts, direct questions, qualified help when needed, and one next step that can actually be completed.`},
 {heading:'A practical next-step sequence',body:`First, confirm immediate safety. Second, identify whether the need is emergency, clinical, housing, referral, transportation, financial, or family support. Third, gather only the minimum information needed for the next call. Fourth, contact the appropriate provider or professional. Finally, write down what was confirmed, what remains uncertain, and the next follow-up date.`},
 {heading:'Safety, licensure, and outcome boundaries',body:commonBoundary}
],keyTakeaways:[directAnswer,'Recovery housing and referral support do not replace emergency, detox, medical, or licensed clinical care.','Clear questions and written expectations reduce avoidable confusion.','Dignity, privacy, and realistic next steps matter more than promises.'],practicalNextSteps:['Call 911 for immediate danger or call/text 988 for crisis support.','Write down the exact housing, referral, or support question that needs an answer.','Ask the provider to explain current services, availability, expectations, costs, and boundaries.','Use a secure approved process before sharing sensitive health information.'],reflectionPrompt:`Which part of ${baseTitle.toLowerCase()} needs a direct answer before the next decision can be made?`,faq:[{question:`${question}`,answer:directAnswer},{question:'Is this medical or treatment advice?',answer:'No. This is general education and recovery-support navigation, not medical advice, diagnosis, treatment, detox, therapy, or emergency care.'},{question:'What if someone is in immediate danger or crisis?',answer:'Call 911 for immediate danger. Call or text 988 for mental health or substance use crisis support.'},{question:'Does this guarantee Dianne’s Place has space or provides a specific service?',answer:'No. Availability, fit, current services, and any future licensed capabilities must be confirmed directly and cannot be guaranteed by an educational resource.'}],contentAtoms:['atom-crisis-boundary','atom-pre-license-boundary','atom-dignity-first','atom-source-trust'],atomBlocks:[{id:'atom-crisis-boundary',label:'Crisis boundary',text:'Dianne’s Place is not an emergency service. Use 911 for immediate danger and 988 for mental health or substance use crisis support.'},{id:'atom-pre-license-boundary',label:'Current service status',text:'Public materials focus on recovery housing, structured sober living, referral support, and general education while expanded licensed services remain in development.'},{id:'atom-dignity-first',label:'Dignity-first language',text:'Recovery support should reduce shame, protect privacy, and help people identify a realistic next step.'},{id:'atom-source-trust',label:'Source-aware support',text:'General education must remain separate from medical claims and should direct clinical or crisis needs to qualified help.'}],internalLinks:[{label:'Recovery Housing',href:'/recovery-housing/'},{label:'Referrals',href:'/referrals/'},{label:'Resources',href:'/resources/'},{label:'Contact',href:'/contact/'}],wordTarget:contentType==='quarterly_whitepaper'?1800:contentType==='monthly_pillar'?1400:contentType==='weekly_article'?1000:700,contentPromise:`a ${typeLabel.toLowerCase()} that gives a direct answer for decisions ${decisionContext}, ${lens}, clear safety boundaries, and a realistic next step`,disclaimerBlock:`${commonBoundary} Recovery outcomes vary.`,sourceIds:['source-988-lifeline','source-samhsa'],claimIds:[],licensureModeAllowed:['pre_license','licensed_provider']});
item.validation={...(item.validation||{}),eligible:true,blockers:[],warnings:[`Deterministic post-2026 ${contentType} generated through the protected native workflow and continuity hardener.`],continuityHardener:'v1'};
cal.generatedAt=`${date}T00:00:00.000Z`;fs.writeFileSync(calPath,JSON.stringify(cal,null,2)+'\n');fs.writeFileSync(reportPath,JSON.stringify({schema_version:'1.0',run_date:date,status:'HARDENED_POST_2026_ITEM',item_id:id,slug,content_type:contentType,topic_id:topicId,lens,decision_context:decisionContext,publication_authority:'EXISTING_VALIDATED_DIANNE_CONTENT_SYSTEM'},null,2)+'\n');console.log(`[continuity:harden] ${id} -> ${contentType} / ${slug}`);
