#!/usr/bin/env node
import fs from 'node:fs';
const cal=JSON.parse(fs.readFileSync('data/content/content_calendar.json','utf8')),contract=JSON.parse(fs.readFileSync('data/continuity/post_2026_continuity_contract.json','utf8')),errors=[],future=(cal.items||[]).filter(x=>x.scheduledAt>='2027-01-01');
const ids=new Set(),slugs=new Set(),dates=new Map(),titles=new Set();
for(const x of future){if(ids.has(x.id))errors.push(`duplicate-id:${x.id}`);ids.add(x.id);if(slugs.has(x.slug))errors.push(`duplicate-slug:${x.slug}`);slugs.add(x.slug);dates.set(x.scheduledAt,(dates.get(x.scheduledAt)||0)+1);titles.add(x.title);if(x.status!=='approved')errors.push(`status:${x.id}`);if(x.publishMode!=='auto_if_validated')errors.push(`publish-mode:${x.id}`);if(x.validation?.eligible!==true)errors.push(`validation:${x.id}`);if(!x.routeTarget?.includes(x.slug))errors.push(`route:${x.id}`);if(!Array.isArray(x.licensureModeAllowed)||!x.licensureModeAllowed.includes('pre_license'))errors.push(`licensure:${x.id}`);if(!x.disclaimerBlock?.toLowerCase().includes('not medical advice')&&!x.disclaimerBlock?.toLowerCase().includes('not a substitute'))errors.push(`disclaimer:${x.id}`);if(x.directAnswer?.length<120)errors.push(`direct-answer:${x.id}`);if((x.sections||[]).length<5)errors.push(`sections:${x.id}`);}
for(const [d,n] of dates)if(n!==1)errors.push(`items-per-day:${d}:${n}`);
if(contract.native_generator_protected!==true||contract.one_item_per_day!==true)errors.push('contract');
if(future.length>10&&titles.size/future.length<0.8)errors.push(`title-diversity:${titles.size}/${future.length}`);
const report={schema_version:'1.0',run_date:new Date().toISOString().slice(0,10),status:errors.length?'FAIL':future.length?'PASS_WITH_FUTURE_ITEMS':'PASS_NO_FUTURE_ITEMS_YET',original_2026_records:(cal.items||[]).filter(x=>x.scheduledAt<='2026-12-31').length,future_records:future.length,unique_future_titles:titles.size,duplicate_ids:future.length-ids.size,duplicate_slugs:future.length-slugs.size,one_item_per_day:[...dates.values()].every(x=>x===1),protected_native_generator:contract.native_generator_protected,errors};fs.writeFileSync('data/continuity/post_2026_continuity_report.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));if(errors.length)process.exit(1);
